module.exports = {
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  extends: [
    'eslint-config-react-app/base',
    'react-app',
    'plugin:prettier/recommended',
    'plugin:react-hooks/recommended',
  ],
  plugins: ['prettier', 'react-hooks'],
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  globals: {
    Parse: 'writable',
    jasmine: 'writable',
    window: 'writable',
    document: 'writable',
    localStorage: 'writable',
    FormData: 'writable',
    FileReader: 'writable',
    Blob: 'writable',
    navigator: 'writable',
  },
  rules: {
    'prettier/prettier': [
      'error',
      {
        printWidth: 120,
        singleQuote: true,
        trailingComma: 'es5',
        bracketSpacing: true,
        tabWidth: 2,
        semi: true,
        endOfLine: 'lf',
        arrowParens: 'always',
      },
    ],
    curly: 'error',
    'prefer-arrow-callback': 'error',
    'arrow-parens': ['error', 'always'],
    'arrow-spacing': 'error',
    'quote-props': ['error', 'as-needed'],
    'no-floating-decimal': 'error',
    'func-call-spacing': ['error', 'never'],
    'no-use-before-define': [
      'error',
      {
        functions: false,
        variables: false,
      },
    ],
    'spaced-comment': [
      'warn',
      'always',
      {
        exceptions: ['/', '*'],
      },
    ],
    'block-spacing': 'warn',
    'no-shadow': 'off',
    '@typescript-eslint/no-shadow': ['error'],
    '@typescript-eslint/no-unused-vars': ['warn'],
    'no-nested-ternary': 'warn',
    'brace-style': 'warn',
    'no-mixed-operators': 'warn',
    'no-multi-spaces': 'warn',
    'no-extra-parens': 'off',
    'template-curly-spacing': 'warn',
    'no-trailing-spaces': 'warn',
    'no-whitespace-before-property': 'warn',
    'no-multiple-empty-lines': 'warn',
    'no-mixed-spaces-and-tabs': 'warn',
    'no-extra-semi': 'warn',
    'comma-spacing': [
      'warn',
      {
        before: false,
        after: true,
      },
    ],
    'jsx-quotes': ['warn', 'prefer-double'],
    'no-tabs': 'warn',
    'no-else-return': 'warn',
    'padding-line-between-statements': [
      'warn',
      {
        blankLine: 'always',
        prev: '*',
        next: 'return',
      },
    ],
    'no-var': 'error',
    'no-unused-vars': 'off',
    'import/no-anonymous-default-export': [
      'error',
      {
        allowArray: false,
        allowArrowFunction: true,
        allowAnonymousClass: true,
        allowAnonymousFunction: true,
        allowCallExpression: true, // The true value here is for backward compatibility
        allowLiteral: false,
        allowObject: true,
      },
    ],
    'react-hooks/exhaustive-deps': 'warn',
  },
};
