spring:
    datasource.driverClassName: org.postgresql.Driver
    groovy.template.check-template-location: false
    aop:
        proxy-target-class: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show_sql: false
        open-in-view: false
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
#      jakarta.persistence.validation.mode: none

logging:
    level:
        org.hibernate: error
        org.springframework: INFO
        trainual.userservice: INFO