package trainual.userservice.api.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import trainual.userservice.dto.FeedbackDto;
import trainual.userservice.dto.FeedbackRequestDto;
import trainual.userservice.service.FeedbackService;

import java.util.List;

@RestController
@RequestMapping(value = "/v1/feedback/")
public class UserNicknameController {

    //TODO get user nickname generated by AI

}
